import asyncio
import random
import string
import logging
import os
import aiohttp
from aiohttp import web
from datetime import datetime
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler,
    ContextTypes, MessageHandler, filters, ConversationHandler,
)

BOT_TOKEN = os.environ.get("BOT_TOKEN", "")
OWNER_ID = int(os.environ.get("OWNER_ID", "0"))
PORT = int(os.environ.get("PORT", "10000"))

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN not set")

SEARCH_TIMEOUT = 45
CHECK_DELAY = 0.05
MAX_RESULTS = 5
BATCH_SIZE = 20
CONCURRENT_LIMIT = 15
WORD_INPUT = 1

logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)

TAKEN_5 = {
    "apple","hello","world","admin","users","tests","music","video","photo",
    "games","sport","money","trade","crypt","block","chain","token","nfts","meta",
    "viral","trend","style","fashi","model","actor","movie","shows","stars","space",
    "earth","ocean","river","mount","forest","flora","fauna","plant","fruit","berry",
    "grape","mango","lemon","melon","peach","plums","cherry","dates","olive","onion",
    "carrot","beans","wheat","bread","pizza","pasta","sushi","steak",
    "salad","soups","cakes","candy","sweet","sugar","honey","cream","cheese","butter",
    "water","juice","drink","glass","bottle",
    "table","chair","lamps","clock","watch","phone",
    "doors","walls","roofs","floor","house","homes","rooms","yards","garden","parks",
    "roads","paths","track","trail","drive","rides","bikes","boats","ships","plane",
    "train","buses","taxis","truck","cargo","fleet","wheels","motor","engine","speed",
    "quick","rapid","swift","flash","blaze","spark","flame","burns","heats",
    "colds","snows","storm","rains","cloud","winds","sunny","light","shiny",
    "glows","shine","glare","gleam","moons","comet","orbit",
    "galax","nebul","quark","atoms","force","power","energy",
    "solar","lunar","tidal","waves","sound","noisy","quiet","peace","calms",
    "happy","smile","laugh","bliss","merry","cheer","jolly","jokes",
    "funny","humor","comic","clown","smirk","grins","teeth","mouth","noses",
    "faces","heads","hands","wrist","elbow","knees","ankle","heels",
    "backs","chest","heart","brain","minds","think","knows",
    "learn","study","teach","tutor","coach","guide","expert","maste",
    "elite","prime","super","ultra","mega","giga","hyper","extra","grand",
    "great","major","chief","bosss","ruler","kingg","queen",
    "royal","crown","sword","shield","armor","knight","warrior","fight","battle","combat",
    "siege","forts","tower","locks","keys","vault","safes",
    "banks","chest","boxes","cases","packs","bags","sacks","trunk","crates",
    "tools","knife","blade","razor","drill","hammer","screw","nails","bolts",
    "wires","cords","cable","fiber","laser","radar","sonar","beacon","pulse",
    "codes","bytes","bits","pixel","image","frame","scene","shots","clips","films",
    "reels","tapes","discs","album","songs","lyric","verse","chorus","rhyme",
    "beats","tempo","rhyth","dance","moves","steps","twirl","swirl","swing","salsa",
    "tango","waltz","disco","funky","groov","jazzy","blues","rocks","metal",
    "indie","folks","souls","gospel","choir","opera","arias","sings",
    "vocal","voice","speak","talks","chats","texts","words","terms","names","title",
    "label","brand","logos","marks","signs","badge","flags","posters","cards",
    "decks","plays","rules","score","goals","wins","loses","draws",
    "match","round","final","champ","trophy","medal","prize","award","bonus","gifts",
    "wraps","deals","sales","shops","store","malls","market",
    "stock","share","bonds","funds","asset","value","price","costs","rates",
    "fees","taxes","dues","bills","coins","cents","bucks","zeros",
    "units","items","goods","wares","stuff","thing","parts","piece","slice","chunk",
    "block","brick","stone","rocks","gravel","soils","clays",
    "slime","gooey","stick","glue","paste","resin","oils","fats",
    "paint","tints","shade","hues","color","tones","pales","fades",
    "ashes","smoke","fumes","vapor","steam","mists","foggy",
    "dusky","dawns","dusks","noons","night","darks","black","white","grays",
    "brown","green","blues","pinks","purpl","viole","indig","cyan","teals",
    "amber","beige","cream","ivory","pearl","goldd","silve","bronz","coppe","rusty",
    "iron","steel","alumin","titan","zincs","leads","nickl","cobal","chrom",
    "silic","carbo","oxyge","nitro","hydro","heliu","neon","argon",
    "radon","urani","pluto","radium","polon","bismo","thall","mercu",
    "plati","palla","iridi","osmiu","rheni","tungs","tanta","hafni","zirco",
    "yttri","scand","titani","vana","manga","ferro","nicke","coppe",
    "galli","germa","arsen","selen","bromi","rubid","stron",
    "niobi","molyb","techn","ruthe","rhodi","cadmi","indiu",
    "antim","tellu","iodin","cesiu","bariu","latha","ceriu","prase",
    "neody","prom","samar","europ","gadoli","terbi","dyspr","holmi","erbiu","thuli",
    "ytter","lutet","reniu","bismu","polon","astat","franc","radiu","actin",
    "thori","proto","neptu","ameri","curiu","berke","calif","einst",
    "fermi","mende","nobel","lawre","ruther","dubni","seabo","bohri","hasse","meitn",
    "darms","roent","copern","nihon","flero","mosco","liver","tenne","oganess",
    "alpha","beta","gamma","delta","sigma","omega","theta","kappa","lambda",
    "tauus","upsil","phiss","chiss","psiss","aleph","beth","gimel",
    "dalet","heiss","zayin","chett","tettt","yoddd","kaphh","lamed",
    "nunns","samek","ayinn","pehhh","tsade","qophh","reshe","shinn","tavvv",
    "first","second","third","fourt","fifth","sixth","seven","eight","ninth","tenth",
    "eleven","twelv","thirt","fifte","sixte","ninet","twent",
    "thirt","forty","fifty","sixty","hundr","thous","milli",
    "micro","nanoo","picoo","femto","atto","zepto","yocto","ronna","quetta",
    "kilo","mega","giga","tera","peta","exa","zetta","yotta","bronto","geopa",
    "monday","tuesd","wedne","thurs","frida","satur","sunda","janua","febru","march",
    "april","mayyy","junee","jully","augus","septe","octob","novem","decem","winte",
    "sprin","summe","autum","falls","years","month","weeks","dayss","hours","minut",
    "secon","momen","epoch","eras","times","dates","clock","watch","timer","alarm",
    "agess","cycle","phase","stage","steps","level","grade","rankk","class",
    "order","group","types","kinds","sorts","forms","modes","style","ways","means",
    "tools","aids","helps","fixes","cures","heals","mends","patch","repai","build",
    "makes","creat","shape","molds","casts","forge","weld","glues",
    "tapes","tacks","stitc","sewss","weave","knits","braid","plait","twist",
    "turns","spins","rolls","loops","knots","binds","ties","wraps","folds","bends",
    "curve","arcss","waves","swell","surge","riser","falls","drops","drips","flows",
    "drain","pours","spill","splash","spray","shoot","burst","blast","crash","smash",
    "break","crack","split","snaps","tears","rips","shred","chops","slices","dices",
    "mince","grind","crush","pound","press","squeez","wring","screw","tight",
    "loose","slack","flopp","softt","hardd","firmm","solid","stiff","rigid","tough",
    "rough","coars","crude","rawss","plain","simpl","basic","core","basal",
    "roots","bases","found","grund","basis","start","begin","onset","birth","origi",
    "sourc","cause","reason","motive","drive","might","stren","vigor",
    "energ","zestt","zeall","ardor","fervr","passi","lustt","crave","thirs","hungr",
    "appet","taste","flavo","aroma","scent","smell","odors","reekk","stink",
    "fragr","perfu","balms","incen","myrrh","muskk","civet","casto","beave",
    "whale","jaspe","agate","onyxx","opall","pearls","coral",
    "ivory","ebony","teaks","mahog","walnu","oakss","maple","birch","beech","cedar",
    "pines","firss","spruc","hemlo","yewss","hicko","elmss","popla","willo",
    "cypre","larch","redwo","seqou","baoba","acaci","mimos","wiste","locust","honey",
    "cassia","senna","tamar","carob","mesqu","alder","bassw","linden","tulip","magnol",
    "dogwo","sassa","sourr","bitte","salty","spicy","tangy","zesty","savor",
    "tasty","yummy","delic","gourm","feast","banqu","repas","meals","lunch","dinne",
    "break","brunc","snack","nibbl","munch","crunc","chews","gulps","swall","digest",
    "absor","assim","metab","catab","anabo","synth","groww","devel","matu",
    "ripen","ferme","curee","smoke","dryss","salts","pickl","canss","jars",
    "freez","chill","cools","icess","snows","froze","glaci","polar","arctic","tundr",
    "taiga","alpin","monta","hilly","plain","plate","basin","valle","gorge","canyo",
    "ravine","gulch","wadii","oasis","desert","dune","sands","beach","coast","shore",
    "cliff","bluff","crag","scree","talus","ledge","shelf","reefs","atoll","lagoo",
    "fjord","estua","delta","marsh","swamp","mires","fens","moors","heath",
    "meado","prair","savan","grass","herbs","shrub","bushs","trees","woods","grove",
    "orcha","viney","field","farmm","ranch","range","graze","pastu","crop","yield",
    "harve","reap","sowss","plant","tilll","ploug","harrow","culti","irriga","drain",
    "ferti","manur","compo","mulch","prune","graft","buddd","layer","shoot",
    "leave","stems","barks","twigs","branc","trunk","crowns","canop","folia","blade",
    "petio","stalk","spike","racem","corym","umbel","head","capit","cymes","panicle",
    "drupe","pomes","legum","grain","caryo","nutss","acorn","seeds",
    "spore","pollen","ovule","embry","endos","peric","testa","hilum","radic","plumu",
    "epico","hypoc","cotyl","nodes","inter","budss","axill","termi","later","adven",
    "tapro","fibro","aerial","buttr","tubers","bulbs","corms","rhizo","stolo",
    "runne","sucke","cutti","buddi","tissu","cultu","clone","hybri",
    "varie","speci","genus","famil","order","phylu","kingd","domai",
    "biome","ecosy","habit","niche","troph","produ","consum","decom","scaven","paras",
    "symbi","mutua","commen","ammens","preda","herbi","carniv","omniv","insec","frugi",
    "foliv","necta","polli","graniv","mollu","pisci","sangu","zooph","sapro","detri",
    "litho","chemo","photo","auto","heter","mixo","facul","oblig","aerob","anaer",
    "mesop","therm","psych","halop","acido","alkal","neutr","osmot","xerop","hydro",
    "hygro","mesic","aqua","marin","terre","aeria","arbore","scans","fossor",
    "cursor","volan","natat","amphi","crepu","diurn","noctu","cathe",
    "vespe","matut","anthel","dawns","dusks","darkk",
}

TAKEN_6 = {
    "google","amazon","netflix","spotify","applee","teslaa","spacex","nasa","elon","musk",
    "donald","trump","joebiden","obama","putin","zelen","macron","merkel","boris","johnson",
    "modi","rahul","sachin","dhoni","virat","rohit","messi","ronaldo","neymar","mbappe",
    "lebron","jordan","kobe","curry","durant","harden","westbr","davis","gianni","luka",
    "tatum","embiid","jokic","butler","adeba","herro","lowry","strus","vincent",
    "martin","robinson","rubio","garlan","allen","mobley","markka","levert","osman",
    "lopez","portis","conna","beasl","matthe","highsm",
    "crypto","bitcoin","ethereum","solana","cardano","ripple","litecoin","dogecoin","shiba","monero",
    "binance","coinbase","kraken","bybit","okx","kucoin","huobi","gateio","bitfin",
    "ledger","trezor","metamask","phantom","trust","wallet","safepal","argent","rainbow","coinomi",
    "exodus","atomic","jaxx","mycel","electrum","bitpay","brd","edge","zen","guarda",
    "uniswap","pancake","sushi","curve","aave","compound","maker","dai","tether","usdc",
    "usdt","busd","frax","trueusd","paxos","gemini","circle","centre","wbtc","renbtc",
    "synthe","chainlink","band","tellor","api3","dia","nest","uma","augur","gnosis",
    "polymarket","azuro","betfury","stake","rollbit","roobet","bcgame","bet365","pinnacle",
    "bovada","draftkings","fanduel","betmgm","caesars","pointsbet","wynnbet","barstool","foxbet","unibet",
    "poker","blackjack","roulette","baccarat","craps","slots","bingo","keno","lottery","raffle",
    "jackpot","million","billion","trillion","zillion","gazillion","infinity","eternal","forever","always",
    "never","sometimes","often","rarely","seldom","usually","frequently","occasionally","constantly","periodically",
    "regularly","daily","weekly","monthly","yearly","hourly","nightly","annual","biweekly",
    "fortnight","decade","century","millennium","epoch","eon","age","era","period","stage",
    "phase","cycle","season","term","session","semester","quarter","trimester","half",
    "whole","total","entire","complete","full","partial","incomplete","broken","damaged","destroyed",
    "ruined","wrecked","demolished","devastated","annihilated","obliterated","eradicated","eliminated","removed","deleted",
    "erased","wiped","cleared","cleaned","purged","flushed","drained","emptied","vacated","abandoned",
    "deserted","forsaken","neglected","ignored","overlooked","missed","lost","found","discovered","invented",
    "created","made","built","constructed","assembled","fabricated","manufactured","produced","generated","synthesized",
    "composed","written","authored","penned","drafted","drawn","sketched","painted","sculpted","carved",
    "engraved","etched","printed","published","issued","released","launched","debuted","premiered","introduced",
    "presented","showed","displayed","exhibited","demonstrated","performed","executed","accomplished","achieved","attained",
    "reached","obtained","acquired","gained","earned","won","secured","procured","purchased","bought",
    "sold","traded","exchanged","bartered","swapped","transferred","shifted","moved","relocated","transported",
    "shipped","delivered","sent","mailed","posted","dispatched","forwarded","redirected","routed","guided",
    "led","directed","managed","controlled","regulated","governed","ruled","commanded","ordered","dictated",
    "prescribed","recommended","suggested","advised","counseled","consulted","informed","notified","alerted","warned",
    "cautioned","reminded","prompted","urged","encouraged","motivated","inspired","stimulated","provoked","triggered",
    "caused","induced","forced","compelled","obliged","required","demanded","requested","asked","questioned",
    "queried","inquired","investigated","examined","inspected","checked","verified","confirmed","validated","authenticated",
    "certified","accredited","licensed","approved","authorized","permitted","allowed","granted","given","provided",
    "supplied","furnished","equipped","armed","prepared","ready","set","go","start","begin",
    "commence","initiate","originate","generate","produce","create","form","shape","mold","cast",
    "forge","weld","solder","braze","glue","paste","tape","tack","staple","stitch",
    "sew","weave","knit","crochet","braid","plait","twist","turn","spin","roll",
    "loop","knot","bind","tie","wrap","fold","bend","curve","arch","wave",
    "swell","surge","rise","fall","drop","drip","flow","stream","run","pour",
    "spill","splash","spray","shoot","burst","blast","crash","smash","break","crack",
    "split","snap","tear","rip","shred","chop","slice","dice","mince","grind",
    "crush","pound","press","squeeze","wring","twist","screw","tighten","loosen","slacken",
    "flop","soften","harden","firm","solidify","stiffen","toughen","roughen","coarsen","crudify",
    "simplify","complicate","complexify","sophisticate","refine","purify","cleanse","clarify","filter","strain",
    "sift","sort","classify","categorize","organize","arrange","order","systematize","structure","format",
    "layout","design","plan","scheme","plot","diagram","chart","graph","map","model",
    "prototype","sample","specimen","example","instance","case","illustration","demonstration","exhibition","display",
    "show","presentation","performance","execution","accomplishment","achievement","attainment","realization","fulfillment","completion",
    "conclusion","termination","cessation","end","finish","close","closure","ending","finale","epilogue",
    "aftermath","consequence","result","outcome","effect","impact","influence","affect","change","alter",
    "modify","adjust","adapt","convert","transform","transfigure","metamorphose","evolve","develop","grow",
    "mature","ripen","age","ferment","cure","smoke","dry","salt","pickle","can",
    "jar","bottle","freeze","chill","cool","ice","snow","frost","glaciate","polarize",
    "magnetize","electrify","ionize","catalyze","oxidize","reduce","hydrolyze","dehydrate","hydrate","saturate",
    "dissolve","melt","fuse","weld","solder","braze","anneal","temper","harden","quench",
    "polish","buff","shine","gloss","glaze","varnish","lacquer","paint","stain","dye",
    "tint","tone","shade","hue","color","pigment","dyestuff","colorant","stain","tinge",
    "touch","trace","hint","suggestion","implication","inference","deduction","conclusion","judgment","decision",
    "verdict","ruling","finding","determination","resolution","settlement","agreement","contract","treaty","pact",
    "accord","concord","harmony","unity","solidarity","cohesion","adhesion","coherence","consistency","congruity",
    "compatibility","conformity","compliance","obedience","submission","yielding","surrender","capitulation","defeat","loss",
    "failure","deficiency","lack","absence","want","need","requirement","necessity","essential","prerequisite",
    "condition","stipulation","provision","clause","term","article","section","paragraph","sentence","phrase",
    "word","letter","character","symbol","sign","mark","token","emblem","badge","insignia",
    "logo","brand","trademark","copyright","patent","license","permit","charter","franchise","concession",
    "privilege","right","entitlement","claim","title","deed","document","record","file","dossier",
    "archive","registry","catalog","directory","index","list","roll","roster","schedule","timetable",
    "calendar","agenda","itinerary","program","syllabus","curriculum","course","lesson","lecture","seminar",
    "workshop","tutorial","training","drill","exercise","practice","rehearsal","preparation","readiness","fitness",
    "health","wellness","wholeness","soundness","strength","vigor","vitality","energy","force","power",
    "might","potency","capacity","capability","ability","skill","talent","gift","aptitude","faculty",
    "knack","dexterity","adroitness","deftness","proficiency","expertise","mastery","command","control","dominion",
    "authority","jurisdiction","sway","influence","leverage","clout","pull","weight","importance","significance",
    "consequence","moment","weightiness","gravity","seriousness","solemnity","dignity","majesty","grandeur",
    "magnificence","splendor","glory","brilliance","radiance","luster","sheen","glow","gleam","glint",
    "sparkle","twinkle","shimmer","glimmer","flicker","flash","flare","blaze","flame","fire",
    "inferno","conflagration","holocaust","cataclysm","catastrophe","disaster","calamity","tragedy","misfortune","adversity",
    "hardship","difficulty","trouble","problem","issue","matter","concern","worry","anxiety","stress",
    "tension","pressure","strain","burden","load","weight","onus","responsibility","duty","obligation",
    "commitment","dedication","devotion","allegiance","loyalty","fidelity","faithfulness","constancy","steadfastness","perseverance",
    "persistence","tenacity","determination","resolve","resolution","will","volition","choice","option","alternative",
    "possibility","probability","likelihood","chance","odds","prospect","hope","expectation","anticipation","aspiration",
    "ambition","goal","aim","objective","target","mark","bullseye","destination","terminus","endpoint",
    "boundary","border","frontier","limit","bounds","confines","perimeter","circumference","periphery","edge",
    "brink","verge","threshold","doorstep","gate","portal","entrance","entry","access","admission",
    "ingress","introduction","initiation","induction","installation","investiture","coronati
